apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  namespace: als
  annotations:
    build: "20250607_114251"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: node
          image: node:20.17.0
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: node-auth-secret
                  key: AUTH_SECRET
          command:
            - sh
            - -c
            - |
              set -e
              git clone https://github.com/wsva/als_next.js_build /home/node/app
              cd /home/node/app
              echo 'DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:5432/alsdb' > .env
              echo 'AUTH_SECRET="${AUTH_SECRET}"' >> .env
              echo 'AUTH_TRUST_HOST=true' >> .env
              node server.js
          ports:
            - containerPort: 3000